server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pawoo0211/msa-practice-config.git
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, busrefresh
